### ISSUE TITLE
Release code for Backend Server

### ISSUE THREAD

**Issue by DreiDe** [HiddenMotives/ProxyChecker#5]
Would it be possible to release the code that is running on the API backend server? I would like to build a similar tool that can determine the anonymity of a proxy. I know that there are some public APIs available and in theory I could also utilise yours, but I want to host everything myself. 

Maybe some hints on how your system works would already be enough. 
Which server is the application running (ngnix, apache)?
Which method is used to find out how secure a proxy is?
Why is it possible to connect to your server thrue almost every Proxy while e.g. 207.154.231.211:8080 is not able to connect to e.g. ipapi.co. Has this something to do with Cloudflare?

**Comment by HiddenMotives** [comment]
The code for the backend is really simple which is why I haven't posted it.

But to answer your questions:
Which method is used to find out how secure a proxy is?
-> The request headers are analyzed to determine whether or not the proxy is leaking your IP address.

Why is it possible to connect to your server thrue almost every Proxy while e.g. 207.154.231.211:8080 is not able to connect to e.g. ipapi.co. Has this something to do with Cloudflare?
-> If your using a public proxy it may be blocked by certain websites and services. Even though that proxy may seem "ALIVE" the IP address associated with the proxy might be blacklisted from the service your trying to access.
